id = "sql"
name = "SQL"
schema_version = 1
version = "1.1.2"
authors = ["nervenes", "notpeter", "phileix", "tammyxiong"]
description = "SQL language support."
repository = "https://github.com/nervenes/zed-sql"

[grammars.sql]
repository = "https://github.com/nervenes/tree-sitter-sql"
commit = "6dfca8b6dcb196d943c10e9cabab25e60232d332"
