name = "SQL"
grammar = "sql"
path_suffixes = ["sql"]
line_comments = ["-- "]
brackets = [
    { start = "(", end = ")", close = true, newline = false },
    { start = "BEGIN", end = "END", close = true, newline = true },
]
